# Copyright (c) 2018 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# travis-ci.org CI unit tests integration configuration file.

language: python
sudo: required

# Force xenial dist, since between dists Travis will make CI-breaking changes
dist: xenial

# On Xenial, xvfb should be started using the services syntax.  Previously, we
# had started it directly in the tests/run_travis.sh script.
# See https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb
services:
  - xvfb

matrix:
  include:
  - python: "2.7"
    env: QT_TEST_VER=4
  - python: "2.7"
    env: QT_TEST_VER=5
  - python: "3.7"
    env: QT_TEST_VER=5

install:
  - pip install -r tests/ci_requirements.txt

# command to run tests
script: tests/run_travis.sh
# Only run coveralls if we actually ran tests. Otherwise this breaks coveralls it seems.
after_success: bash <(curl -s https://codecov.io/bash)